### ISSUE TITLE
there is no package called ‘Biostrings’

### ISSUE THREAD

**Issue by biochembryony** [Proteomicslab57357/UniprotR#34]
Hi, 

Thank you for making this package available to use. I am excited to use it for my research, however I get the following issue when I try to use it.

Error: package or namespace load failed for ‘UniprotR’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
there is no package called ‘Biostrings’

This message appears when I try to load UniprotR in an R notebook, using the command **library(UniprotR)**. I have tried using the command **install.packages("Biostrings")**, but I get the message "Warning in install.packages :
  package ‘Biostrings’ is not available for this version of R". I have the latest version of R Studio (Beagle Scouts) - is this incompatible or am I doing something else wrong?

Hope you can offer some help, any advice would be greatly appreciated.

**Comment by lkalmar** [comment]
Had the same problem, just had to install Biostrings:
`BiocManager::install("Biostrings")`

You will probably have one more error, missing the GenomicAlignments package, install the same way:
`BiocManager::install("GenomicAlignments")`

If you don't have the BiocManager installed, you have to install it before these:
`install.packages("BiocManager")`

**Comment by MohmedSoudy** [comment]
Hi @biochembryony,
This problem is similar to #14 
It's due to dependency "alakazam" version 1.1.0 while UniprotR requires alakazam version 1.0.0. This problem will be solved in the next version of UniprotR and can be solved now by installing alakazam before installing UniprotR using   install.packages("https://cran.r-project.org/src/contrib/Archive/alakazam/alakazam_1.0.0.tar.gz", repo=NULL, type="source")
